### Model Prediction Result 

In [ ]:
# 각 사고별 최적의 모델 선정 
all_acc_model = { "기계사고" : [Random_Forset_model_MCHN_ACDNT_OCRN_CNT, XGBoost_model_MCHN_ACDNT_OCRN_CNT, CatBoost_model_MCHN_ACDNT_OCRN_CNT],
                   "기타사고" : [Random_Forset_model_ETC_OCRN_CNT, XGBoost_model_ETC_OCRN_CNT, CatBoost_model_ETC_OCRN_CNT],
                  "둔상" : [Random_Forset_model_BLTRM_OCRN_CNT, XGBoost_model_BLTRM_OCRN_CNT, CatBoost_model_BLTRM_OCRN_CNT],
                  "사고부상" : [Random_Forset_model_ACDNT_INJ_OCRN_CNT, XGBoost_model_ACDNT_INJ_OCRN_CNT, CatBoost_model_ACDNT_INJ_OCRN_CNT],
                  "질병외" : [Random_Forset_model_EXCL_DISEASE_OCRN_CNT, XGBoost_model_EXCL_DISEASE_OCRN_CNT, CatBoost_model_EXCL_DISEASE_OCRN_CNT],
                  "탈것사고" : [Random_Forset_model_VHC_ACDNT_OCRN_CNT, XGBoost_model_VHC_ACDNT_OCRN_CNT, CatBoost_model_VHC_ACDNT_OCRN_CNT],
                  "낙상" : [Random_Forset_model_HRFAF_OCRN_CNT, XGBoost_model_HRFAF_OCRN_CNT, CatBoost_model_HRFAF_OCRN_CNT],
                  "단순주취" : [Random_Forset_model_DRKNSTAT_OCRN_CNT, XGBoost_model_DRKNSTAT_OCRN_CNT, CatBoost_model_DRKNSTAT_OCRN_CNT],
                  "동물곤충사고" : [Random_Forset_model_ANML_INSCT_ACDNT_OCRN_CNT, XGBoost_model_ANML_INSCT_ACDNT_OCRN_CNT, CatBoost_model_ANML_INSCT_ACDNT_OCRN_CNT],
                  "동승자사고" : [Random_Forset_model_FLPS_ACDNT_OCRN_CNT, XGBoost_model_FLPS_ACDNT_OCRN_CNT, CatBoost_model_FLPS_ACDNT_OCRN_CNT],
                  "보행자사고" : [Random_Forset_model_PDST_ACDNT_OCRN_CNT, XGBoost_model_PDST_ACDNT_OCRN_CNT, CatBoost_model_PDST_ACDNT_OCRN_CNT],
                  "열상" : [Random_Forset_model_LACRTWND_OCRN_CNT, XGBoost_model_LACRTWND_OCRN_CNT, CatBoost_model_LACRTWND_OCRN_CNT],
                  "오토바이사고" : [Random_Forset_model_MTRCYC_ACDNT_OCRN_CNT, XGBoost_model_MTRCYC_ACDNT_OCRN_CNT, CatBoost_model_MTRCYC_ACDNT_OCRN_CNT],
                  "운전사사고" : [Random_Forset_model_DRV_ACDNT_OCRN_CNT, XGBoost_model_DRV_ACDNT_OCRN_CNT, CatBoost_model_DRV_ACDNT_OCRN_CNT],
                  "자전거사고" : [Random_Forset_model_BCYC_ACDNT_OCRN_CNT, XGBoost_model_BCYC_ACDNT_OCRN_CNT, CatBoost_model_BCYC_ACDNT_OCRN_CNT],
                  "중독사고" : [Random_Forset_model_POSNG_OCRN_CNT, XGBoost_model_POSNG_OCRN_CNT, CatBoost_model_POSNG_OCRN_CNT],
                  "추락사고" : [Random_Forset_model_FALLING_OCRN_CNT , XGBoost_model_FALLING_OCRN_CNT , CatBoost_model_FALLING_OCRN_CNT ],
                  }

In [ ]:
# 사고별 최적의 모델 분포 결과  
for data, model in all_acc_model.items():
    # 각 모델 predict 
    y_pred_1 = model[0].predict(last_day_df)
    y_pred_2 = model[1].predict(last_day_df)
    y_pred_3 = model[2].predict(last_day_df)

    # 사고별 최적의 모델 분포 
    print (f"       {data} 분포 예측 결과        ")
    unique_1, cnt_1 = np.unique(y_pred_1, return_counts = True)
    uni_cnt_dict_1 = dict(zip(unique_1, cnt_1))
    print (f"Random Forset 모델 분포 결과 : {uni_cnt_dict_1}")

    unique_2, cnt_2 = np.unique(y_pred_2, return_counts = True)
    uni_cnt_dict_2 = dict(zip(unique_2, cnt_2))
    print (f"XGBoost 모델 분포 결과 : {uni_cnt_dict_2}")

    unique_3, cnt_3 = np.unique(y_pred_3, return_counts = True)
    uni_cnt_dict_3 = dict(zip(unique_3, cnt_3))
    print (f"CatBoost 모델 분포 결과 : {uni_cnt_dict_3}")

    print("*"*45)

       기계사고 분포 예측 결과        
Random Forset 모델 분포 결과 : {0: 4538, 1: 687}
XGBoost 모델 분포 결과 : {0: 4403, 1: 822}
CatBoost 모델 분포 결과 : {0: 4705, 1: 520}
*********************************************
       기타사고 분포 예측 결과        
Random Forset 모델 분포 결과 : {0: 3451, 1: 1774}
XGBoost 모델 분포 결과 : {0: 3014, 1: 2211}
CatBoost 모델 분포 결과 : {0: 4515, 1: 710}
*********************************************
       둔상 분포 예측 결과        
Random Forset 모델 분포 결과 : {0: 4551, 1: 674}
XGBoost 모델 분포 결과 : {0: 4080, 1: 1145}
CatBoost 모델 분포 결과 : {0: 4705, 1: 520}
*********************************************
       사고부상 분포 예측 결과        
Random Forset 모델 분포 결과 : {0: 4547, 1: 678}
XGBoost 모델 분포 결과 : {0: 4413, 1: 812}
CatBoost 모델 분포 결과 : {0: 4540, 1: 685}
*********************************************
       질병외 분포 예측 결과        
Random Forset 모델 분포 결과 : {0: 4896, 1: 329}
XGBoost 모델 분포 결과 : {0: 4813, 1: 412}
CatBoost 모델 분포 결과 : {0: 4865, 1: 360}
*********************************************
       탈것사고 분포 예측 결과        
Random

In [ ]:
# 분포결과 및 점수를 확인하여 상위 1개를 이용한 모델 답안지 추출
def final_grid_result_ex2 (name, use_model_1, data):
    
    # 원형 모델 데이터프레임 
    result_DF = data.copy()

    # 격자 추출 
    Grid_IDS = data["GRID_ID"].unique()

    print(f"{name} 격자 추출")
    print("*"*30)

    # 매월 말일에 label이 1(사건이 발생한)인 격자 추출
    for mon in range(1, 12):

        # 매월 말일 + 사건이 발생한 격자 추출
        predict_df=result_DF.loc[result_DF['MONTH'] == mon, :]

        # 매월 발생하는 사건중 상위 5개 격자만 추출 (예측확률 기준)
        pred_proba = use_model_1.predict_proba(predict_df) 
        pred_proba_df = pd.DataFrame(pred_proba).sort_values(by = 1, ascending=False)
        result_index = pred_proba_df[pred_proba_df[1] >= 0.5][:5].index 

        # 각 월말 날짜 추출
        month_day = result_DF.loc[(result_DF["MONTH"] == mon)]

        # 정답 격자 
        print([month_day["MONTH"].iat[0], month_day["DAY"].iat[0]])
        print(Grid_IDS[result_index])
        print() 
        

In [ ]:
final_grid_result_ex2 ("기계사고", Random_Forset_model_MCHN_ACDNT_OCRN_CNT, last_day_df)

기계사고 격자 추출
******************************
[1, 31]
[]

[2, 28]
[385525]

[3, 31]
[395527 396524 394527 396526 393527]

[4, 30]
[395527 394527 396524 396526 393527]

[5, 31]
[395527 396524 396526 394527 393527]

[6, 30]
[394527 395527 396526 396524 393527]

[7, 31]
[395527 394527 396524 396526 393527]

[8, 31]
[395527 396524 394527 396526 393527]

[9, 30]
[395527 394527 396524 396526 393527]

[10, 31]
[385525 395527 396524 394529 393527]

[11, 30]
[395527 396524 394527 396526 393527]

